filter:
  include_antigen_keys:
    - H1_HA
    - H1_HA_NewCaledonia1999
    - H1_Solomon_HA
    - H3_HA_Wisconsin2005
    - H4_Hubei_HA
    - H7_HK16_HA
    - H9_HA_HongKong1073_1999
  require_antigen_sequence: true
  min_trainable_records_per_group: 2
  min_unique_labels_per_group: 2
